on script load:
	wait 0.1 seconds
	broadcast "&bHolographic Displays (Skript Test)"
	broadcast "&aLoading all data!"
	wait 1 second
	broadcast "&bAll data was loaded!"
	if text from "https://pastebin.com/raw/mYGKcmFy" is not "1.2":
		set {_text} to text from "https://pastebin.com/raw/mYGKcmFy"
		broadcast "&9[&bHD&9] &bYou don't have the latest version (%{_text}%)! Download it from our GitHub page!"
	set {hdskript} to "enabled"

on script unload:	
	clear {hdskript}

on join:
	if text from "https://pastebin.com/raw/mYGKcmFy" is not "1.2":
		set {_text} to text from "https://pastebin.com/raw/mYGKcmFy"
		message "&9[&bHD&9] &bYou don't have the latest version (%{_text}%)! Download it from our GitHub page!"


command /hd [<text>] [<text>] [<text>]:
	permission: hd.use
	trigger:
		if arg-1 is not set:
			message "&bHolographic Displays (Skript Version)"
			message "&9Made by: ryanrox333"
			message "&9Version: &b1.2"
			message "&9Database: &b%{database}%"
			message "&bUse ""/hd help"" for commands!"
		if arg-1 is "help":
			message "&bHD - (1.2)"
			message "&b/hd create &9- &bCreate a Hologram!"
			message "&b/hd delete &9- &bDelete a Hologram!"
			message "&b/hd editholo &9- &bChange the text on your hologram!"
			message "&b/hd list &9- &bList all Holograms!"
			message "&b/hd download &9- &bDownload the new updates!"
		if arg-1 is "create":
			if arg-2 is not set:
				if arg-3 is not set:
					message "&cUse /hd create <Name> <Text> [Use "";"" to make a new line!]"
					stop
			if arg-2 is set:
				if arg-3 is not set:
					message "&cUse /hd create <Name> <Text> [Use "";"" to make a new line!]"
					stop
			if arg-2 is set:
				if arg-3 is set:
					message "&9[&bHD&9] &bCreated a hologram named %arg-2%!"
					set {_colorcodes} to "%arg-3%"
					replace all "&" with "§" in {_colorcodes}
					set {location.%arg-2%} to block above player
					set {text.%arg-2%} to "%{_colorcodes}%"
					create holo object "%{_colorcodes}%" with id "%arg-2%" at block above player
					wait 0.1 seconds
					clear {_colorcodes}
					add arg-2 to {hololist::*}
					stop
		if arg-1 is "delete":
			if arg-2 is not set:
				message "&cUse /hd delete <Name>"
				stop
			if arg-2 is set:
				if {hololist::*} contains "%arg-2%":
					delete holo object "%arg-2%"
					message "&9[&bHD&9] &bDeleted %arg-2%!"
					remove arg-2 from {hololist::*}
					stop
				if {hololist::*} does not contain "%arg-2%":
					message "&cThis is not a valid Hologram name!"
					stop
		if arg-1 is "list":
			message "&9[&bHD&9]"
			message "%{hololist::*}%"
		if arg-1 is "download":
			if text from "https://pastebin.com/raw/mYGKcmFy" is not "1.2":
				set {_text} to text from "https://pastebin.com/raw/mYGKcmFy"
				message "&9[&bHD&9] &bDownload %{_text}% from here: <link:https://github.com/ryanrox333/HD-skript/tree/master>https://github.com/ryanrox333/HD-skript/tree/master"
			if text from "https://pastebin.com/raw/mYGKcmFy" is "1.2":
				message "&9[&bHD&9] &bYou have the Latest version so you dont need to do this!"
		if arg-1 is "editholo":
			if arg-2 is not set:
				message "&cUse /hd editholo <Name> <New Text>"
			if arg-2 is set:
				if arg-3 is set:
					if {hololist::*} contains "%arg-2%":
						set {text.%arg-2%} to "%arg-3%"
						message "&9[&bHD&9] &b%arg-2%'s text has been changed!"
						stop
					if {hololist::*} does not contain "%arg-2%":
						message "&cThis is not a valid Hologram name!"
						stop
		Else:
			if arg-1 is set:
				if arg-1 is not "create":
					if arg-1 is not "delete":
						if arg-1 is not "list":
							if arg-1 is not "download":
								if arg-1 is not "help":
									if arg-1 is not "editholo":
										message "&9[&bHD&9] &bUnknown Command! Use /hd help!"


every 5 seconds:
	loop {hololist::*}:
		delete holo object "%loop-value%"
		wait 0.1 seconds
		create holo object "%{text.%loop-value%}%" with id "%loop-value%" at {location.%loop-value%}
